FROM python:3.12-slim

WORKDIR /opt/app

COPY ./python/requirements.txt requirements.txt

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./python/src src

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
