[package]
name = "rust_sqrt"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]

[tool.hints]
definitions = "proto/oracle.proto"  # required
#cairo_output = "src"
#oracle_lock = "Oracle.lock"

